title: Prompt Surfing DRG
description: Class Website for Winter 2024 Prompt Surfing DRG
theme: just-the-docs

url: https://RuoxiShang.github.io/promptsurfing

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/RuoxiShang/promptsurfing
